### PR TITLE
Transcode local files

### LINKED ISSUE #85: Deprecate makes_derivatives and transform_file

### PR DESCRIPTION
**Pull request by jcoyne**
This allows us to do the transcoding on a working copy and not download
the original from Fedora to do initial transcoding.

Fixes #85

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Test failure. Mark that one to skip it on Travis?

**Comment by jcoyne** [comment]
All fixed up.

**Comment by terrellt** [comment]
My only concern here is deprecation warnings. What's our policy for things in projecthydra?

**Comment by jcoyne** [comment]
@terrellt I don't know how to backport this stuff and keep the old stuff going.  I've just given up and said "this is a new major version. stuff will break".

**Comment by terrellt** [comment]
Should we cut 2.1 beforehand, then?

**Comment by jcoyne** [comment]
@terrellt We could, but I don't think we have to. 2.0 came out Aug 15 and it was mostly changes to support PCDM.  Merging this PR certainly doesn't preclude releasing a 2.1 at a later date, it just can't be from HEAD.

**Pull request merged**
